- name: Install docker and some dependencies
  raw: "curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun"
  tags: install

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
  tags: install

- name: pip install docker
  pip:
    name: docker
  tags: install



- name: Create Mysql container
  docker_container:
    name: mysql
    image: mysql
    state: started
    recreate: yes
  tags: mysql

- name: Create nginx container
  docker_container:
    name: nginx4
    image: nginx
    state: started
    recreate: yes
    interactive: yes
    published_ports:
      - "8872:80"
  tags: nginx

- name: Install docker and some dependencies
  raw: "docker logs nginx4 "
  tags: logs

- name: Run the equivalent of "apt-get clean" as a separate step
  apt:
    clean: yes